/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 09 15:40:03 GMT 2025
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.BufferManagerImplementation;
import org.example.Page;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BufferManager_ESTest extends BufferManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(186, "org.example.BufferManager");
      bufferManagerImplementation0.unpinPage(186);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(1, "PI_GmBjB");
      bufferManagerImplementation0.markDirty(1809);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(1, "PI_GmBjB");
      Page page0 = bufferManagerImplementation0.getPage(1955);
      assertNull(page0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(2895, "org.example.BufferManager");
      Page page0 = bufferManagerImplementation0.createPage();
      Page page1 = bufferManagerImplementation0.getPage(0);
      assertSame(page1, page0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(1, "");
      Page page0 = bufferManagerImplementation0.createPage();
      assertEquals(0, page0.getPid());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(1, "PI_GmBjB");
      bufferManagerImplementation0.createPage();
      // Undeclared exception!
      bufferManagerImplementation0.createPage();
  }
}
