/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 09 15:42:47 GMT 2025
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.PageImplementation;
import org.example.Row;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PageImplementation_ESTest extends PageImplementation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(0, 0);
      pageImplementation0.getRow(2555);
      assertEquals(0, pageImplementation0.getPid());
      assertTrue(pageImplementation0.isFull());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(77, 77);
      pageImplementation0.insertRow((Row) null);
      int int0 = pageImplementation0.insertRow((Row) null);
      assertEquals(1, int0);
      assertEquals(77, pageImplementation0.getPid());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(411, 411);
      int int0 = pageImplementation0.insertRow((Row) null);
      assertEquals(0, int0);
      
      pageImplementation0.getRows();
      assertEquals(411, pageImplementation0.getPid());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(959, 959);
      byte[] byteArray0 = new byte[9];
      Row row0 = new Row(byteArray0, byteArray0);
      int int0 = pageImplementation0.insertRow(row0);
      assertEquals(0, int0);
      
      Row row1 = pageImplementation0.getRow((byte)0);
      assertNotNull(row1);
      assertEquals(959, pageImplementation0.getPid());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(0, 0);
      int int0 = pageImplementation0.getPid();
      assertTrue(pageImplementation0.isFull());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation((-2140), (-1));
      int int0 = pageImplementation0.getPid();
      assertTrue(pageImplementation0.isFull());
      assertEquals((-2140), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(77, 77);
      boolean boolean0 = pageImplementation0.isFull();
      assertEquals(77, pageImplementation0.getPid());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(0, 0);
      boolean boolean0 = pageImplementation0.isFull();
      assertTrue(boolean0);
      assertEquals(0, pageImplementation0.getPid());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation((-193), (-193));
      int int0 = pageImplementation0.insertRow((Row) null);
      assertEquals((-193), pageImplementation0.getPid());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(670, 670);
      pageImplementation0.getRow(0);
      assertFalse(pageImplementation0.isFull());
      assertEquals(670, pageImplementation0.getPid());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(670, 670);
      pageImplementation0.getRows();
      assertEquals(670, pageImplementation0.getPid());
      assertFalse(pageImplementation0.isFull());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation(670, 670);
      int int0 = pageImplementation0.getPid();
      assertFalse(pageImplementation0.isFull());
      assertEquals(670, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PageImplementation pageImplementation0 = new PageImplementation((-193), (-193));
      pageImplementation0.getRow((-193));
      assertTrue(pageImplementation0.isFull());
      assertEquals((-193), pageImplementation0.getPid());
  }
}
