/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 09 15:45:03 GMT 2025
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.example.BufferManagerImplementation;
import org.example.Utilities;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utilities_ESTest extends Utilities_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Utilities.loadDataset("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[1];
      FileSystemHandling.shouldAllThrowIOExceptions();
      // Undeclared exception!
      try { 
        Utilities.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to create storage file: C:\\Users\\Priya\\Desktop\\database.bin
         //
         verifyException("org.example.BufferManagerImplementation", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Utilities.loadDataset((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Utilities.loadDataset("!{");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("File path cannot be null");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(4107, "File path cannot be null");
      bufferManagerImplementation0.createPage();
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "File path cannot be null");
      Utilities.setBufferManager(bufferManagerImplementation0);
      Utilities.loadDataset("File path cannot be null");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[3];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("File path cannot be null");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      Utilities.main(stringArray0);
      Utilities.loadDataset("File path cannot be null");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      BufferManagerImplementation bufferManagerImplementation0 = new BufferManagerImplementation(4096, "!{");
      // Undeclared exception!
      try { 
        Utilities.loadDataset("!{");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Utilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Utilities utilities0 = new Utilities();
  }
}
